logging:
  level: INFO
  loggers:
    com.trainingcenter: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: 123
  url: jdbc:mysql://dorime.mooo.com:3306/ElGoog
  validationQuery: "SELECT 1"